import type { Metadata } from "next";
import "./globals.css";
import {StartMockWorker} from "@/component/mockServer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <StartMockWorker>
          {children}
        </StartMockWorker>
      </body>
    </html>
  );
}
